### ISSUE TITLE
just a small refactor

### ISSUE THREAD

**Issue by mhimehdi** [CryptoKass/NoobChain-Tutorial-Part-1#1]
instead of the loop 
you can use a java stream: in stringutil class
  IntStream.range(0,hash.length).mapToObj(i->Integer.toHexString(0xff&hash[i]))
                    .map(hex->hex.length()==1?hexString.append('0'):hexString.append(hex)).count();

**Comment by CryptoKass** [comment]
Yeah that's much shorter and nicer, I Initially opted out of using stream for the tutorial because I thought it would be harder for people to see what the method was doing. 
Considering changing it :) thanks

**Comment by CryptoKass** [comment]
Good suggestion but I'm opting to keep readability over shorter alternative.
