### ISSUE TITLE
break while loop in mineBlock func

### ISSUE THREAD

**Issue by ylkjick532428** [CryptoKass/NoobChain-Tutorial-Part-1#2]
I think we need to add a statement 
this.timeStamp = new Date().getTime();
else this calculateHash() always the same hash, can't break while loop.

public String calculateHash() {
		this.timeStamp = new Date().getTime();
		String calculatedhash = StringUtil.applySha256( 
				previousHash +
				Long.toString(timeStamp) +
				data 
				);
		return calculatedhash;
	}

**Comment by CryptoKass** [comment]
It wouldn't seem we would want that, as calculate hash is also used when verifying the Blocks. We need to be able to check the value. 
Make sure to include nonce in the calculate hash method, then increment the nonce ( an integer variable ) in the mine block method and include it in the hash, this way the method will change :). 

	public String calculateHash() {
		String calculatedhash = StringUtil.applySha256( 
				previousHash +
				Long.toString(timeStamp) +
				Integer.toString(nonce) + 
				data 
				);
		return calculatedhash;
	}
	public void mineBlock(int difficulty) {
		String target = StringUtil.getDificultyString(difficulty); //Create a string with difficulty * "0" 
		while(!hash.substring( 0, difficulty).equals(target)) {
			nonce ++;
			hash = calculateHash();
		}
		System.out.println("Block Mined!!! : " + hash);
	}

**Comment by ylkjick532428** [comment]
Yes, that's could be better
